name: update-builder-image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    name: "build"
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build toolchain image
        run: docker build --ulimit nofile=65536 -t the_aarch64_builder .
      - name: Tag toolchain image
        run: docker image tag the_aarch64_builder ${{ secrets.DOCKERHUB_USERNAME }}/the_aarch64_builder:${{ github.event.inputs.version }}
      - name: Upload toolchain image
        run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/the_aarch64_builder:${{ github.event.inputs.version }}